name: Build and Deploy Spring Boot App to Azure

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do c√≥digo
        uses: actions/checkout@v4

      - name: Setup Java 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'
          cache: maven

      - name: Build com Maven
        run: mvn clean package -DskipTests
        working-directory: SpringBoot/api-produtos

      - name: Upload do artefato
        uses: actions/upload-artifact@v4
        with:
          name: app-jar
          path: SpringBoot/api-produtos/target/*.jar

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download do artefato
        uses: actions/download-artifact@v4
        with:
          name: app-jar

      - name: Login na Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_1684CE2BCA004FBEA3EBAD71C776EB42 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_60A17446F61441CD9A0D461296C66ECC }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_ABB30AE313A742C3A398732AC0AB917D }}

      - name: Deploy no Azure App Service
        uses: azure/webapps-deploy@v3
        with:
          app-name: bootcamp-produtos-HigorCabral
          slot-name: Production
          package: '*.jar'
